export { default as Layout } from './Layout'
export { default as Home } from './Home'
export { default as Services } from './Services'
export { default as Blog } from './Blog'
export { default as Contact } from './Contact'
export { default as AboutUs } from './AboutUs'