export { default as Layout } from './Layout'
export { default as Home } from './Home'
export { default as Projects } from './Projects'
export { default as Blog } from './Blog'
export { default as Contact } from './Contact'